name: Patches

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apply-patches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clone
      run: |
        sudo apt-get update
        sudo apt-get install git
        git clone 'https://github.com/nsxiv/nsxiv.git'
    - name: apply-patches
      # FIXME: only apply the latest patch rather than everything
      # TODO: exit with non-zero status if any of the patches fails to apply
      run: |
        cd nsxiv
        find ../patches -type f -name '*.patch' |
          xargs -I{} /bin/sh -c 'git apply --check {} 2>/dev/null || echo "[FAILED]: $(basename {})"'
